import sys
import os
import csv



this_script_dir = os.path.dirname(os.path.realpath(__file__))


def item_tile_is_collectible(t):
    return t == 15



def encode_map_data(path, output):
    with open(path) as csvfile:
        reader = csv.reader(csvfile)

        collectible_item_tiles = []

        for row in reader:
            output.write('DB ')

            first = True

            for num in row:
                if not first:
                    output.write(', ')

                first = False

                if int(num) < 16:
                    output.write('$0')
                    output.write(hex(int(num))[2:])
                else:
                    output.write('$')
                    output.write(hex(int(num))[2:])

                if item_tile_is_collectible(int(num)):
                    collectible_item_tiles.append(int(num))

                    if len(collectible_item_tiles) > 8:
                        print("warning: too many collectible items assigned to room")
                        print("\tin file: " + path)


            output.write("\n")



for subdir in os.listdir(this_script_dir + "/../data/map"):
    dirfiles = []

    for map_data in os.listdir(this_script_dir + "/../data/map/" + subdir):
        if not "~" in map_data:
            dirfiles.append(map_data)

    dirfiles.sort(key=lambda f: int(''.join(filter(str.isdigit, f))))

    with open(this_script_dir + "/../source/rom10/" + "r10_maps_" + subdir + ".asm", "w") as outp:
        outp.write(";; generated by encode_room_layouts.py\n\n")

        outp.write("r10_room_data_" + subdir + "::\n")

        for fname in dirfiles:
            outp.write(";;" + fname + "\n")
            encode_map_data(this_script_dir + "/../data/map/" + subdir + "/" + fname, outp)

        outp.write("r10_room_data_" + subdir + "_end::\n")
